routes/admin.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\PostController;
use App\Models\Comment;
use Encore\Admin\Grid\Displayers\Prefix;
use Illuminate\Support\Facades\Route;

use PhpParser\Node\Name;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/



Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'check_login_admin'], function () {

// Route::group(['middleware' => ['check_login_admin'], 'as' => 'admin.'], function () {

    // Route::group(['prefix' => 'admin.',  'middleware' => 'CheckAdminLogin'], function(){


    Route::get('login', [AuthController::class, 'getLogin'])->name('login');
    Route::post('login', [AuthController::class, 'postLogin'])->name('login.handle');
    Route::post('logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');


    Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
        Route::get('/', [CategoryController::class, 'index'])->name('index');
        Route::get('/create', [CategoryController::class, 'create'])->name('create');
        Route::post('/store', [CategoryController::class, 'store'])->name('store');
        Route::get('/{id}/show', [CategoryController::class, 'show'])->name('show');
        Route::get('/{id}/edit', [CategoryController::class, 'edit'])->name('edit');
        Route::put('/{id}/update', [CategoryController::class, 'update'])->name('update');
        Route::delete('/{id}/delete', [CategoryController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {
        Route::get('/', [PostController::class, 'index'])->name('index');
        Route::get('/create', [PostController::class, 'create'])->name('create');
        Route::post('/store', [PostController::class, 'store'])->name('store');
        Route::get('/{id}/show', [PostController::class, 'show'])->name('show');
        Route::get('/{id}/edit', [PostController::class, 'edit'])->name('edit');
        Route::put('/{id}/update', [PostController::class, 'update'])->name('update');
        Route::delete('/{id}/delete', [PostController::class, 'destroy'])->name('destroy');
        Route::post('/{id}/save-feature', [PostController::class, 'saveFeature'])->name('save-feature');
    });

    Route::group(['prefix' => 'comments', 'as' => 'comments.'], function () {
        Route::get('/', [Comment::class, 'index'])->name('index');
    });
});








// Route::group(['middleware' => ['check_login_admin'] , 'as' => 'admin.'], function () {

//     Route::resource('category','CategoryController');

// 	// Admin Dashboard
// 	Route::get('/', [DashboardController::class, 'index'])->name('dashboard');	

//     // route for module Category
// 	Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
//         Route::get('/', [CategoryController::class, 'index'])->name('index');
//         Route::get('/create', [CategoryController::class, 'create'])->name('create');
//         Route::post('/store', [CategoryController::class, 'store'])->name('store');
//         Route::get('/{id}/show', [CategoryController::class, 'show'])->name('show');
//         Route::get('/{id}/edit', [CategoryController::class, 'edit'])->name('edit');
//         Route::put('/{id}/update', [CategoryController::class, 'update'])->name('update');
//         Route::delete('/{id}/delete', [CategoryController::class, 'destroy'])->name('destroy');
//     });

//     Route::group(['prefix' => 'posts', 'as' => 'posts.'], function() {
//         Route::get('/', [PostController::class, 'index'])->name('index');
//         Route::get('/create', [PostController::class, 'create'])->name('create');
//         Route::post('/store', [PostController::class, 'store'])->name('store');
//         Route::get('/{id}/show', [PostController::class, 'show'])->name('show');
//         Route::get('/{id}/edit', [PostController::class, 'edit'])->name('edit');
//         Route::put('/{id}/update', [PostController::class, 'update'])->name('update');
//     });

// });

routes/web.php
<?php

use App\Http\Controllers\AjaxApiController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\ProfileController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\SubscribePostController;
use App\Http\Controllers\UserQueueController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\TestSendMailController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/




require __DIR__ . '/admin.php';

require __DIR__ . '/auth.php';


Route::get('/', [HomeController::class, 'index'])->name('home');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::get('/posts', [PostController::class, 'index'])->name('posts.index');

// Route::PostController::class->group(function () {
//     Route::get('/posts', 'show');
//     Route::post('/post', 'store');
// });

// Route::prefix('/posts')-> group(function() {
//     Route::get('/', [PostController::class, 'index'])->name('index');

// })-> name('posts.');


Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {
    Route::get('/', [PostController::class, 'index'])->name('index');
    // ---> URL : 127.0.0.1:8000/posts (method : GET)

    Route::get('/create', [PostController::class, 'create'])->name('create');
    // ---> URL : 127.0.0.1:8000/posts/create (method : GET)


    Route::post('/', [PostController::class, 'store'])->name('store');
    // ---> URL : 127.0.0.1:8000/posts (method: POST)


    Route::get('/{id}', [PostController::class, 'show'])->name('show');
    // ---> URL : 127.0.0.1:8000/posts/{post ID}   (method : GET)


    Route::get('/{id}/edit', [PostController::class, 'edit'])->name('edit');
    // ---> URL : 127.0.0.1:8000/posts/{ ID}/edit  (method: GET)

    Route::put('/{id}', [PostController::class, 'update'])->name('update');
    // ---> URL : 127.0.0.1:8000/posts/{ ID}  (method: PUT)


    Route::delete('/{id}', [PostController::class, 'destroy'])->name('destroy');
    // ---> URL : 127.0.0.1:8000/posts/{ ID}  (method : DELETE)
});

Route::get('/category/{id}/post', [CategoryController::class, 'index'])->name('category-list-post');


Route::get('/category', [CategoryController::class, 'index'])->name('category-list');


Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'handleLoginForm'])->name('login.handle');
Route::post('logout', [LoginController::class, 'logout'])->name('logout');

Route::get('profile', [ProfileController::class, 'showProfile'])->name('profile')->middleware('check_login_user');

Route::post('subscribe_post', [SubscribePostController::class, 'store'])->name('subscribe_post');

Route::get('test-send-mail', [TestSendMailController::class, 'send'])->name('test-send-mail');

Route::get('/ajax', [AjaxApiController::class, 'index'])->name('api.index');


Route::get('/test-email', [JobController::class, 'index'])->name('test-email');

// Route::get('test-email', 'JobController@processQueue');

Route::get('/file-import', [UserController::class, 'importView'])->name('import-view');
Route::post('/import', [UserController::class, 'import'])->name('import');
Route::get('/export-users', [UserController::class, 'exportUsers'])->name('export-users');

// Route::post('/import', UserController::class, 'importView')->name('import');


Route::get('/import-with-queue',[UserQueueController::class, 'import_with_queue'])->name('import-with-queue');
Route::post('/import-queue', [UserQueueController::class, 'import-queue'])->name('import-queue');

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Post\StorePostRequest;
use App\Http\Requests\Admin\Post\UpdatePostRequest;
use App\Models\Category;
use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $data = [];


        $posts = Post::with('category')->orderBy('created_at', 'DESC')->paginate(11);
        $data['posts'] = $posts;
        return view('backend.posts.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories = Category::pluck('name', 'id');
        $data['categories'] = $categories;

        return view('backend.posts.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StorePostRequest $request)
    {
        // dd(Storage::url('posts/thumbnail_post_1681302026.jpg'));
        $postInsert = [
            'name' => $request->post_name,
            'category_id' => $request->post_category_id,
            // 'thumbnail' => $request -> post_thumbnail,
            'content' => $request->post_content
        ];

        // uploadthumbnail 
        $extension = $request->post_thumbnail->extension();
        $fileName = 'thumbnail_post_' . time() . '.' . $extension;
        $thumbnailPath = $request->file('post_thumbnail')->storeAs(
            'posts',
            $fileName,
            ['disk' => 'public']
        );
        $postInsert['thumbnail'] = $thumbnailPath;

        try {
            // Insert into data to table category (successful)
            Post::create($postInsert);

            return redirect()->route('admin.posts.index')
                ->with('sucess', trans('message.store_post_success'));
        } catch (\Exception $ex) {
            // Insert into data to table category (fail)
            Log::error($ex->getMessage());
            return redirect()->back()->with('error', $ex->getMessage());
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $data = [];
        $post = Post::findOrFail($id);
        $data['post'] = $post;


        return view('backend.posts.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $data = [];

        $categories = Category::pluck('name', 'id');
        $data['categories'] = $categories;

        $post = Post::findOrFail($id);
        $data['post'] = $post;

        return view('backend.posts.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdatePostRequest $request, string $id)
    {
        try {
            $post = Post::findOrFail($id);

            $postThumbnailOld = $post->thumbnail;

            // Set value for field name
            $post->name = $request->post_name;
            $post->category_id = $request->post_category_id;
            $post->content = $request->post_content;

            // check neu có gửi hình ảnh lên thì lưu vào trong folder storage
            if ($request->post_thumbnail) {
                $extension = $request->post_thumbnail->extension();
                $fileName = 'thumbnail_post_' . time() . '.' . $extension;
                $thumbnailPath = $request->file('post_thumbnail')->storeAs(
                    'posts',
                    $fileName,
                    ['disk' => 'public']
                );
                $post->thumbnail = $thumbnailPath;
            }

            $post->save();

            // xóa hình cũ sau khi upload thành công và lưu vào database thành công
            if ($request->post_thumbnail && $postThumbnailOld) {
                Storage::disk('public')->delete($postThumbnailOld);
            }

            return redirect()->route('admin.posts.index')
                ->with('success', trans('Thành Công'));
        } catch (\Exception $ex) {
            // Have error so will show error message
            return redirect()->back()->with('error', $ex->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        try {
            $post = Post::findOrFail($id);
            $postThumbnail = $post->thumbnail;
            $post->delete();

            // xóa hình ảnh sau khi thực hiên xong thao tác 
            if ($postThumbnail) {
                Storage::disk('public')->delete($postThumbnail);
            }

            return redirect()->route('admin.posts.index')
                ->with('success', trans('Thành Công'));
        } catch (\Exception $ex) {
            // Have error so will show error message
            return redirect()->back()->with('error', $ex->getMessage());
        }
    }
    
    public function saveFeature($id){
        $post=Post::findOrFail($id);
        $isFeature=$post->is_feature;
        if($isFeature){
            $post->is_feature=false;
        }else{
            $post->is_feature=true;
        }
        $post->save();
        return response()->json(['message'=>'success']);
    }
}

app/Http/Controllers/Api/PostController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Api\StorePostRequest;
use App\Http\Requests\Api\UpdatePostRequest;
use App\Http\Resources\PostResource;
use App\Models\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $posts = Post::select(['id', 'category_id', 'name', 'thumbnail', 'created_at', 'updated_at'])
            ->with('category')
            ->paginate(12);
        return PostResource::collection($posts);

        
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StorePostRequest $request)
    {
        $postInsert = [
            'name' => $request->name,
            'category_id' => $request->category_id,
            'content' => $request->content
        ];

        // uploadthumbnail 
        $extension = $request->thumbnail->extension();
        $fileName = 'thumbnail_post_' . time() . '.' . $extension;
        $thumbnailPath = $request->file('thumbnail')->storeAs(
            'posts',
            $fileName,
            ['disk' => 'public']
        );
        $postInsert['thumbnail'] = $thumbnailPath;

        try {
            // Insert into data to table category (successful)
            $post = Post::create($postInsert);

            return new PostResource($post);
        } catch (\Exception $ex) {
            // Insert into data to table category (fail)
            Log::error($ex->getMessage());
            return response()->json(['erorr' => 'tao bai viet that bai'], 500);
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $posts = Post::findOrFail($id);
        return new PostResource($posts);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        dd($request->all());
        try {
            $post = Post::findOrFail($id);

            $postThumbnailOld = $post->thumbnail;

            // Set value for field name
            $post->name = $request->name;
            $post->category_id = $request->category_id;
            $post->content = $request->content;

            // check neu có gửi hình ảnh lên thì lưu vào trong folder storage
            if ($request->thumbnail) {
                $extension = $request->thumbnail->extension();
                $fileName = 'thumbnail_post_' . time() . '.' . $extension;
                $thumbnailPath = $request->file('post_thumbnail')->storeAs(
                    'posts',
                    $fileName,
                    ['disk' => 'public']
                );
                $post->thumbnail = $thumbnailPath;
            }

            $post->save();

            // xóa hình cũ sau khi upload thành công và lưu vào database thành công
            if ($request->thumbnail && $postThumbnailOld) {
                Storage::disk('public')->delete($postThumbnailOld);
            }

            return new PostResource($post);
        } catch (\Exception $ex) {
            // Have error so will show error message
            return response()->json(['erorr' => 'tao bai viet that bai'], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $posts = Post::findOrFail($id);
        $posts->delete();
        return response()->json(['message' => 'xoa thanh cong']);
    }
}

resources/views/backend/posts/_search.blade.php
<div class="d-flex justify-content-between mb-3">
    <div>
        {{-- create category link --}}
        <a href="{{ route('admin.posts.create') }}" class="btn btn-primary"><i class="fas fa-plus"></i> {{ __('Tạo') }}</a>

        @if(!$posts->isEmpty())
            {{ __('Tổng số bản ghi', ['total' => $posts->count()]) }}
        @endif
    </div>
    <div>
        <form action="{{ route('admin.posts.index') }}" method="get">
            <input type="text" placeholder="" name="name" value="{{ request()->name }}" class="form-control-custom d-inline-block">
            <button type="submit" class="btn btn-primary d-inline-block"><i class="fas fa-search"></i> {{ __('Tìm kiếm') }}</button>
        </form>
    </div>
</div>

resources/views/backend/posts/create.blade.php
@extends('backend.layouts.master')

{{-- set page title --}}
@section('title', __('tạo bài viết'))

{{-- set breadcrumbName --}}
@section('breadcrumbName', __('Danh sách bài viết'))

{{-- set breadcrumbMenu --}}
@section('breadcrumbMenu', __('tạo bài viết'))

{{-- import file css (private) --}}
@push('css')
<link rel="stylesheet" href="/backend/css/categories/category-create.css">
@endpush

@section('content')
{{-- error message --}}
@include('errors.error_message')

<form action="{{ route('admin.posts.store') }}" method="post" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <div class="mb-5">
                    <label for="" class="required">{{ __('Tên bài viết') }}</label>
                    <input type="text" name="post_name" class="form-control">
                    @error('post_name')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-5">
                    <label for="" class="required">{{ __('Số thứ tự category') }}</label>
                    <select name="post_category_id" class="form-control">
                        @foreach ($categories as $categoryId => $categoryName)
                        <option value="{{ $categoryId }}">{{ $categoryName }}</option>
                        @endforeach
                    </select>
                    @error('post_category_id')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror

                </div>

                <div class="mb-5">
                    <label for="" class="required">{{ __('Nhập hình ảnh') }}</label>
                    <input type="file" name="post_thumbnail" class="form-control">
                    @error('post_thumbnail')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
                
                <div class="mb-5">

                    <label for="" class="required">{{ __('Nhập nội dung') }}</label>
                    <input type="text" name="post_content" class="form-control">
                    @error('post_content')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
        </div>
    </div>

    <p><span class="red">(*)</span> {{ __('Bắt buộc') }}</p>

    <div class="form-group">
        <a href="{{ route('admin.posts.index') }}" class="btn btn-secondary"><i class="fas fa-long-arrow-alt-left"></i> <span class="ml-2">{{ __('Trở về') }}</span></a>
        <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> <span class="ml-2">{{ __('Thêm mới') }}</span></button>
    </div>
</form>
@endsection

resources/views/backend/posts/detail.blade.php
@extends('backend.layouts.master')

{{-- set page title --}}
@section('title', 'Detail Posts')

{{-- set breadcrumbName --}}
@section('breadcrumbName', 'Posts Management')

{{-- set breadcrumbMenu --}}
@section('breadcrumbMenu', 'Detail Category')

{{-- import file css (private) --}}
@push('css')

@endpush

@section('content')
    
@endsection

resources/views/backend/posts/edit.blade.php
@extends('backend.layouts.master')

{{-- set page title --}}
@section('title', __(''))

{{-- set breadcrumbName --}}
@section('breadcrumbName', __('Danh sách bài viết'))

{{-- set breadcrumbMenu --}}
@section('breadcrumbMenu', __(''))

{{-- import file css (private) --}}
@push('css')
<link rel="stylesheet" href="/backend/css/categories/category-edit.css">
@endpush

@section('content')
{{-- error message --}}
@include('errors.error_message')

<form action="{{ route('admin.posts.update', $post->id) }}" method="post" enctype="multipart/form-data" >
    @csrf
    @method('PUT')

    <div class="form-group mb-3">
        <div class="row">
            <div class="col-md-4">

                <div class="mb-5">
                    <label for="" class="required">{{ __('Tên bài viết') }}</label>
                    <input type="text" name="post_name" class="form-control" value="{{ old('post_name', $post->name) }}">
                    @error('post_name')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-5">
                    <label for="" class="required">{{ __('Số thứ tự category') }}</label>
                    <select name="post_category_id" class="form-control">
                        @foreach ($categories as $categoryId => $categoryName)
                        <option value="{{ $categoryId }}" {{ old('post_category_id', $post->category_id) == $categoryId ? 'selected' : ''}}>{{ $categoryName }}</option>
                        @endforeach
                    </select>
                    @error('post_category_id')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

                <div class="mb-5">
                    <label for="">{{ __('Nhập hình ảnh') }}</label>
                    <img src="{{ Storage::url($post->thumbnail) }}" alt="{{ $post->name }}">
                    <input type="file" name="post_thumbnail" class="form-control">
                    @error('post_thumbnail')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>


                <div class="mb-5">
                    <label for="" class="required">{{ __('Nhập nội dung') }}</label>
                    <textarea type="text" name="post_content" class="form-control">{{ old('post_content', $post->content) }}</textarea>
                    @error('post_content')
                    <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>

            </div>
        </div>
    </div>

    <p><span class="red">(*)</span> {{ __('Bắt buộc') }}</p>

    <div class="form-group">
        <a href="{{ route('admin.posts.index') }}" class="btn btn-secondary"><i class="fas fa-long-arrow-alt-left"></i> <span class="ml-2">{{ __('Trở về') }}</span></a>
        <button type="submit" class="btn btn-primary"><i class="far fa-edit"></i> <span class="ml-2">{{ __('Cập nhật') }}</span></button>
    </div>
</form>
@endsection

resources/views/backend/posts/index.blade.php
@extends('backend.layouts.master')

{{-- set page title --}}
@section('title', __('message.category_list'))

{{-- set breadcrumbName --}}
@section('breadcrumbName', __('Danh sách bài viết'))

{{-- set breadcrumbMenu --}}
@section('breadcrumbMenu', __('message.category_list'))

{{-- import file css (private) --}}
@push('css')
<link rel="stylesheet" href="/backend/css/categories/category-list.css">
<link rel="stylesheet" href="/css/switch.css">
@endpush

@push('js')
<script>
    function saveFeatureJS(that) {
        var confirmAction = confirm("Are you sure to execute this?");
        if (confirmAction) {
            var URL = $(that).closest('form').attr('action');
            var CSRF = $(that).closest('form').find('input[name="_token"]').val();
            $.ajax({
                type: 'post',
                url: URL,
                data: {
                    _token: CSRF
                },
                success: function(data) {
                    alert('success');
                },
                error: function(err) {
                    alert('error');
                }
            });
        }
    }
</script>
@endpush

@section('content')
{{-- form search --}}
@include('backend.posts._search')

{{-- show message --}}
@if(Session::has('success'))
<p class="text-success">{{ Session::get('success') }}</p>
@endif

{{-- show error message --}}
@if(Session::has('error'))
<p class="text-danger">{{ Session::get('error') }}</p>
@endif

{{-- display list category table --}}
@if($posts->isEmpty())
<p class="red">{{ __('Không tìm thấy dữ liệu') }}</p>
@else
<table id="category-list" class="table table-bordered table-hover table-striped">
    <thead class="bg-info">
        <tr>
            <th class="text-center">#</th>
            <th>Tên bài viết</th>
            <th>Tên category</th>
            <th>Thumbnail</th>
            <th>Bài viết nổi bật</th>
            <th colspan="2">Thao tác</th>
        </tr>
    </thead>
    <tbody>
        @if(!empty($posts))
        @foreach ($posts as $key => $post)
        <tr>
            <td class="text-center">{{ $key+1 }}</td>
            <td>{{ $post->name }}</td>
            <td> {{ $post->category->name}} </td>
            <td><img src="{{ Storage::url($post->thumbnail) }}" alt="{{ $post->name }}" class="img-thumbnail"> </td>
            <td>
                <form method="post" action="{{ route('admin.posts.save-feature', $post->id) }}">
                    @csrf
                    <label class="switch">
                        <input type="checkbox" {{ $post->is_feature ? 'checked' : '' }} onclick="saveFeatureJS(this)">
                        <span class="slider round"></span>
                    </label>
                </form>
            </td>
            <td><a href="{{ route('admin.posts.edit', $post->id) }}" class="btn btn-info btn-common" title="{{ __('message.edit_post') }}"><i class="fas fa-edit"></i> {{ __('Chỉnh sửa') }}</a></td>
            <td>
                <form action="{{ route('admin.posts.destroy', $post->id) }}" method="post">
                    @csrf
                    @method('DELETE')
                    <button type="submit" class="btn btn-danger btn-common" onclick="return confirm('bạn có muốn xóa không ?')"><i class="fas fa-trash-alt"></i> {{ __('Xóa') }}</button>
                </form>
            </td>
        </tr>
        @endforeach
        @endif
    </tbody>
</table>
@endif
@endsection

resources/views/backend/posts/show.blade.php
@extends('layouts.master')

@section('content')


<div class="">
    <p> {{ $post->name }} </p>
    <img src="https://picsum.photos/200/300" alt="{{ $post->name }}">
    <h2>Danh mục</h2>
    <p> {{ $post->category->name}}</p>   
    <h2>Hình ảnh</h2>

</div>






@endsection