routes/admin.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\PostController;
use App\Models\Comment;
use Encore\Admin\Grid\Displayers\Prefix;
use Illuminate\Support\Facades\Route;

use PhpParser\Node\Name;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/



Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'check_login_admin'], function () {

// Route::group(['middleware' => ['check_login_admin'], 'as' => 'admin.'], function () {

    // Route::group(['prefix' => 'admin.',  'middleware' => 'CheckAdminLogin'], function(){


    Route::get('login', [AuthController::class, 'getLogin'])->name('login');
    Route::post('login', [AuthController::class, 'postLogin'])->name('login.handle');
    Route::post('logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');


    Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
        Route::get('/', [CategoryController::class, 'index'])->name('index');
        Route::get('/create', [CategoryController::class, 'create'])->name('create');
        Route::post('/store', [CategoryController::class, 'store'])->name('store');
        Route::get('/{id}/show', [CategoryController::class, 'show'])->name('show');
        Route::get('/{id}/edit', [CategoryController::class, 'edit'])->name('edit');
        Route::put('/{id}/update', [CategoryController::class, 'update'])->name('update');
        Route::delete('/{id}/delete', [CategoryController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {
        Route::get('/', [PostController::class, 'index'])->name('index');
        Route::get('/create', [PostController::class, 'create'])->name('create');
        Route::post('/store', [PostController::class, 'store'])->name('store');
        Route::get('/{id}/show', [PostController::class, 'show'])->name('show');
        Route::get('/{id}/edit', [PostController::class, 'edit'])->name('edit');
        Route::put('/{id}/update', [PostController::class, 'update'])->name('update');
        Route::delete('/{id}/delete', [PostController::class, 'destroy'])->name('destroy');
        Route::post('/{id}/save-feature', [PostController::class, 'saveFeature'])->name('save-feature');
    });

    Route::group(['prefix' => 'comments', 'as' => 'comments.'], function () {
        Route::get('/', [Comment::class, 'index'])->name('index');
    });
});








// Route::group(['middleware' => ['check_login_admin'] , 'as' => 'admin.'], function () {

//     Route::resource('category','CategoryController');

// 	// Admin Dashboard
// 	Route::get('/', [DashboardController::class, 'index'])->name('dashboard');	

//     // route for module Category
// 	Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
//         Route::get('/', [CategoryController::class, 'index'])->name('index');
//         Route::get('/create', [CategoryController::class, 'create'])->name('create');
//         Route::post('/store', [CategoryController::class, 'store'])->name('store');
//         Route::get('/{id}/show', [CategoryController::class, 'show'])->name('show');
//         Route::get('/{id}/edit', [CategoryController::class, 'edit'])->name('edit');
//         Route::put('/{id}/update', [CategoryController::class, 'update'])->name('update');
//         Route::delete('/{id}/delete', [CategoryController::class, 'destroy'])->name('destroy');
//     });

//     Route::group(['prefix' => 'posts', 'as' => 'posts.'], function() {
//         Route::get('/', [PostController::class, 'index'])->name('index');
//         Route::get('/create', [PostController::class, 'create'])->name('create');
//         Route::post('/store', [PostController::class, 'store'])->name('store');
//         Route::get('/{id}/show', [PostController::class, 'show'])->name('show');
//         Route::get('/{id}/edit', [PostController::class, 'edit'])->name('edit');
//         Route::put('/{id}/update', [PostController::class, 'update'])->name('update');
//     });

// });

routes/web.php
<?php

use App\Http\Controllers\AjaxApiController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\ProfileController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\SubscribePostController;
use App\Http\Controllers\UserQueueController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\TestSendMailController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/




require __DIR__ . '/admin.php';

require __DIR__ . '/auth.php';


Route::get('/', [HomeController::class, 'index'])->name('home');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::get('/posts', [PostController::class, 'index'])->name('posts.index');

// Route::PostController::class->group(function () {
//     Route::get('/posts', 'show');
//     Route::post('/post', 'store');
// });

// Route::prefix('/posts')-> group(function() {
//     Route::get('/', [PostController::class, 'index'])->name('index');

// })-> name('posts.');


Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {
    Route::get('/', [PostController::class, 'index'])->name('index');
    // ---> URL : 127.0.0.1:8000/posts (method : GET)

    Route::get('/create', [PostController::class, 'create'])->name('create');
    // ---> URL : 127.0.0.1:8000/posts/create (method : GET)


    Route::post('/', [PostController::class, 'store'])->name('store');
    // ---> URL : 127.0.0.1:8000/posts (method: POST)


    Route::get('/{id}', [PostController::class, 'show'])->name('show');
    // ---> URL : 127.0.0.1:8000/posts/{post ID}   (method : GET)


    Route::get('/{id}/edit', [PostController::class, 'edit'])->name('edit');
    // ---> URL : 127.0.0.1:8000/posts/{ ID}/edit  (method: GET)

    Route::put('/{id}', [PostController::class, 'update'])->name('update');
    // ---> URL : 127.0.0.1:8000/posts/{ ID}  (method: PUT)


    Route::delete('/{id}', [PostController::class, 'destroy'])->name('destroy');
    // ---> URL : 127.0.0.1:8000/posts/{ ID}  (method : DELETE)
});

Route::get('/category/{id}/post', [CategoryController::class, 'index'])->name('category-list-post');


Route::get('/category', [CategoryController::class, 'index'])->name('category-list');


Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'handleLoginForm'])->name('login.handle');
Route::post('logout', [LoginController::class, 'logout'])->name('logout');

Route::get('profile', [ProfileController::class, 'showProfile'])->name('profile')->middleware('check_login_user');

Route::post('subscribe_post', [SubscribePostController::class, 'store'])->name('subscribe_post');

Route::get('test-send-mail', [TestSendMailController::class, 'send'])->name('test-send-mail');

Route::get('/ajax', [AjaxApiController::class, 'index'])->name('api.index');


Route::get('/test-email', [JobController::class, 'index'])->name('test-email');

// Route::get('test-email', 'JobController@processQueue');

Route::get('/file-import', [UserController::class, 'importView'])->name('import-view');
Route::post('/import', [UserController::class, 'import'])->name('import');
Route::get('/export-users', [UserController::class, 'exportUsers'])->name('export-users');

// Route::post('/import', UserController::class, 'importView')->name('import');


Route::get('/import-with-queue',[UserQueueController::class, 'import_with_queue'])->name('import-with-queue');
Route::post('/import-queue', [UserQueueController::class, 'import-queue'])->name('import-queue');

resources/views/backend/layouts/container_header.blade.php
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0">@yield('breadcrumbName', __('Trang chủ'))</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">

          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>
  <!-- /.content-header -->

resources/views/backend/layouts/css.blade.php
{{-- all file css use global  --}}
<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">

<!-- jQuery UI 1.11.4 -->
<link rel="stylesheet" href="/backend/admin_lte/plugins/jquery-ui/jquery-ui.min.css">

<!-- Font Awesome -->
<link rel="stylesheet" href="/backend/admin_lte/plugins/fontawesome-free/css/all.min.css">

<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

<!-- Tempusdominus Bootstrap 4 -->
<link rel="stylesheet" href="/backend/admin_lte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">

<!-- iCheck -->
<link rel="stylesheet" href="/backend/admin_lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css">

<!-- JQVMap -->
<link rel="stylesheet" href="/backend/admin_lte/plugins/jqvmap/jqvmap.min.css">

<!-- Theme style -->
<link rel="stylesheet" href="/backend/admin_lte/dist/css/adminlte.min.css">

<!-- overlayScrollbars -->
<link rel="stylesheet" href="/backend/admin_lte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">

<!-- Daterange picker -->
<link rel="stylesheet" href="/backend/admin_lte/plugins/daterangepicker/daterangepicker.css">

<!-- summernote -->
<link rel="stylesheet" href="/backend/admin_lte/plugins/summernote/summernote-bs4.min.css">

{{-- toastr --}}
<link rel="stylesheet" href="/backend/admin_lte/plugins/toastr/toastr.min.css">

{{-- select2 --}}
<link rel="stylesheet" href="/plugins/select2/select2.min.css">

{{-- common --}}
<link rel="stylesheet" href="/backend/css/common.css">

{{-- declare other file css --}}
@stack('css')

resources/views/backend/layouts/footer.blade.php
<!-- /.content-wrapper -->
<footer class="main-footer">
    <strong>Copyright &copy; {{ date('Y') }} <a href="#">Laravel Demo</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 1.0.0
    </div>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

resources/views/backend/layouts/js.blade.php
{{-- declare all file script use global --}}
<!-- jQuery -->
<script src="/backend/admin_lte/plugins/jquery/jquery.min.js"></script>

<!-- jQuery UI 1.11.4 -->
<script src="/backend/admin_lte/plugins/jquery-ui/jquery-ui.min.js"></script>

<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>

<!-- Bootstrap 4 -->
<script src="/backend/admin_lte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>

<!-- ChartJS -->
<script src="/backend/admin_lte/plugins/chart.js/Chart.min.js"></script>

<!-- Sparkline -->
<script src="/backend/admin_lte/plugins/sparklines/sparkline.js"></script>

<!-- JQVMap -->
<script src="/backend/admin_lte/plugins/jqvmap/jquery.vmap.min.js"></script>
<script src="/backend/admin_lte/plugins/jqvmap/maps/jquery.vmap.usa.js"></script>

<!-- jQuery Knob Chart -->
<script src="/backend/admin_lte/plugins/jquery-knob/jquery.knob.min.js"></script>

<!-- daterangepicker -->
<script src="/backend/admin_lte/plugins/moment/moment.min.js"></script>
<script src="/backend/admin_lte/plugins/daterangepicker/daterangepicker.js"></script>

<!-- Tempusdominus Bootstrap 4 -->
<script src="/backend/admin_lte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>

<!-- Summernote -->
<script src="/backend/admin_lte/plugins/summernote/summernote-bs4.min.js"></script>

<!-- overlayScrollbars -->
<script src="/backend/admin_lte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>

{{-- toastr --}}
<script src="/backend/admin_lte/plugins/toastr/toastr.min.js"></script>

<!-- AdminLTE App -->
<script src="/backend/admin_lte/dist/js/adminlte.js"></script>
<!-- AdminLTE for demo purposes -->
<!-- <script src="/backend/admin_lte/dist/js/demo.js"></script> -->
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
{{-- <script src="/backend/admin_lte/dist/js/pages/dashboard.js"></script> --}}

{{-- select2 --}}
<script src="/plugins/select2/select2.full.min.js"></script>

<script type="text/javascript">

</script>

<script src="/backend/js/common.js"></script>

{{-- declare other file script use private --}}
@stack('js')

resources/views/backend/layouts/master.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <title>@yield('title', 'CMS - Dashboard')</title>

  @include('backend.layouts.css')
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

  <!-- Preloader -->
  <div class="preloader flex-column justify-content-center align-items-center">
    <img class="animation__shake" src="/backend/admin_lte/dist/img/AdminLTELogo.png" alt="AdminLTELogo" height="60" width="60">
  </div>

  @include('backend.layouts.navbar')

  @include('backend.layouts.sidebar')

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    @include('backend.layouts.container_header')

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        @yield('content')
        <!-- /.row (main row) -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  @include('backend.layouts.footer')
</div>
<!-- ./wrapper -->

@include('backend.layouts.js')
</body>
</html>

resources/views/backend/layouts/navbar.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="/backend/admin_lte/dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="/backend/admin_lte/dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="/backend/admin_lte/dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

resources/views/backend/layouts/sidebar.blade.php
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">

            <img src="{{ asset('backend/no-avatar.png') }}" class="img-circle elevation-2" alt="User Image">

        </div>
        <div class="info">
          <a href="{{ route('admin.dashboard') }}" class="d-block">Admin</a>
        </div>
      </div>




      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          {{-- menu for home page --}}
          <li class="nav-item {{ Route::currentRouteName() == 'admin.dashboard' ? 'menu-open' : '' }}">
            <a href="{{ route('admin.dashboard') }}" class="nav-link {{ Route::currentRouteName() == 'admin.dashboard' ? 'active' : '' }}">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                {{ __('Trang chủ') }}
              </p>
            </a>
          </li>

          {{-- menu of category module --}}
           @php
            $routeCategoryArr = [
              'admin.category.index',
              'admin.category.create',
              'admin.category.edit',
              'admin.category.show',
            ];
          @endphp 
          <li class="nav-item {{ in_array(Route::currentRouteName(), $routeCategoryArr) ? 'menu-open' : '' }}">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-list"></i>
              <p>
              {{ __('Danh sách category') }}
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
               <li class="nav-item">
                <a href="{{ route('admin.category.index') }}" class="nav-link {{ Route::currentRouteName() == 'admin.category.index' ? 'active' : '' }}">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{{ __('Danh sách Category') }}</p>
                </a>
              </li> 
              <li class="nav-item">
                <a href="{{ route('admin.category.create') }}" class="nav-link {{ Route::currentRouteName() == 'admin.category.index' ? 'active' : '' }}">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{{ __('Thêm mới Category') }}</p>
                </a>
              </li> 
            </ul>
          </li>

          {{-- menu of post module --}}
           @php
            $routePostArr = [
              'admin.post.index',
              'admin.post.create',
              'admin.post.edit',
              'admin.post.show',
            ];
          @endphp 
          <li class="nav-item {{ in_array(Route::currentRouteName(), $routePostArr) ? 'menu-open' : '' }}">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-list"></i>
              <p>
              {{ __('Danh sách bài viết') }}
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
               <li class="nav-item">
                <a href="{{ route('admin.posts.index') }}" class="nav-link {{ Route::currentRouteName() == 'admin.category.index' ? 'active' : '' }}">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{{ __('Bài viết') }}</p>
                </a>
              </li> 
              <li class="nav-item">
                <a href="{{ route('admin.posts.create') }}" class="nav-link {{ Route::currentRouteName() == 'admin.category.index' ? 'active' : '' }}">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{{ __('Thêm mới bài viết') }}</p>
                </a>
              </li> 
            </ul>
          </li>

          {{-- menu of customer module --}}
          @php
            $routeCommentArr = [
              'admin.comment.index',

            ];
          @endphp
          <li class="nav-item {{ in_array(Route::currentRouteName(), $routeCommentArr) ? 'menu-open' : '' }}">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-users"></i>
              <p>
              {{ __('Lượt comment') }}
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="#" class="nav-link {{ Route::currentRouteName() == 'admin.customer.index' ? 'active' : '' }}">
                  <i class="far fa-circle nav-icon"></i>
                  <p>{{ __('Comment') }}</p>
                </a>
              </li>
            </ul>
          </li>


        </ul>

      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->


  </aside>