routes/admin.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\PostController;
use App\Models\Comment;
use Encore\Admin\Grid\Displayers\Prefix;
use Illuminate\Support\Facades\Route;

use PhpParser\Node\Name;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/



Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'check_login_admin'], function () {

// Route::group(['middleware' => ['check_login_admin'], 'as' => 'admin.'], function () {

    // Route::group(['prefix' => 'admin.',  'middleware' => 'CheckAdminLogin'], function(){


    Route::get('login', [AuthController::class, 'getLogin'])->name('login');
    Route::post('login', [AuthController::class, 'postLogin'])->name('login.handle');
    Route::post('logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');


    Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
        Route::get('/', [CategoryController::class, 'index'])->name('index');
        Route::get('/create', [CategoryController::class, 'create'])->name('create');
        Route::post('/store', [CategoryController::class, 'store'])->name('store');
        Route::get('/{id}/show', [CategoryController::class, 'show'])->name('show');
        Route::get('/{id}/edit', [CategoryController::class, 'edit'])->name('edit');
        Route::put('/{id}/update', [CategoryController::class, 'update'])->name('update');
        Route::delete('/{id}/delete', [CategoryController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {
        Route::get('/', [PostController::class, 'index'])->name('index');
        Route::get('/create', [PostController::class, 'create'])->name('create');
        Route::post('/store', [PostController::class, 'store'])->name('store');
        Route::get('/{id}/show', [PostController::class, 'show'])->name('show');
        Route::get('/{id}/edit', [PostController::class, 'edit'])->name('edit');
        Route::put('/{id}/update', [PostController::class, 'update'])->name('update');
        Route::delete('/{id}/delete', [PostController::class, 'destroy'])->name('destroy');
        Route::post('/{id}/save-feature', [PostController::class, 'saveFeature'])->name('save-feature');
    });

    Route::group(['prefix' => 'comments', 'as' => 'comments.'], function () {
        Route::get('/', [Comment::class, 'index'])->name('index');
    });
});








// Route::group(['middleware' => ['check_login_admin'] , 'as' => 'admin.'], function () {

//     Route::resource('category','CategoryController');

// 	// Admin Dashboard
// 	Route::get('/', [DashboardController::class, 'index'])->name('dashboard');	

//     // route for module Category
// 	Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
//         Route::get('/', [CategoryController::class, 'index'])->name('index');
//         Route::get('/create', [CategoryController::class, 'create'])->name('create');
//         Route::post('/store', [CategoryController::class, 'store'])->name('store');
//         Route::get('/{id}/show', [CategoryController::class, 'show'])->name('show');
//         Route::get('/{id}/edit', [CategoryController::class, 'edit'])->name('edit');
//         Route::put('/{id}/update', [CategoryController::class, 'update'])->name('update');
//         Route::delete('/{id}/delete', [CategoryController::class, 'destroy'])->name('destroy');
//     });

//     Route::group(['prefix' => 'posts', 'as' => 'posts.'], function() {
//         Route::get('/', [PostController::class, 'index'])->name('index');
//         Route::get('/create', [PostController::class, 'create'])->name('create');
//         Route::post('/store', [PostController::class, 'store'])->name('store');
//         Route::get('/{id}/show', [PostController::class, 'show'])->name('show');
//         Route::get('/{id}/edit', [PostController::class, 'edit'])->name('edit');
//         Route::put('/{id}/update', [PostController::class, 'update'])->name('update');
//     });

// });

routes/web.php
<?php

use App\Http\Controllers\AjaxApiController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\ProfileController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\SubscribePostController;
use App\Http\Controllers\UserQueueController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\TestSendMailController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/




require __DIR__ . '/admin.php';

require __DIR__ . '/auth.php';


Route::get('/', [HomeController::class, 'index'])->name('home');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::get('/posts', [PostController::class, 'index'])->name('posts.index');

// Route::PostController::class->group(function () {
//     Route::get('/posts', 'show');
//     Route::post('/post', 'store');
// });

// Route::prefix('/posts')-> group(function() {
//     Route::get('/', [PostController::class, 'index'])->name('index');

// })-> name('posts.');


Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {
    Route::get('/', [PostController::class, 'index'])->name('index');
    // ---> URL : 127.0.0.1:8000/posts (method : GET)

    Route::get('/create', [PostController::class, 'create'])->name('create');
    // ---> URL : 127.0.0.1:8000/posts/create (method : GET)


    Route::post('/', [PostController::class, 'store'])->name('store');
    // ---> URL : 127.0.0.1:8000/posts (method: POST)


    Route::get('/{id}', [PostController::class, 'show'])->name('show');
    // ---> URL : 127.0.0.1:8000/posts/{post ID}   (method : GET)


    Route::get('/{id}/edit', [PostController::class, 'edit'])->name('edit');
    // ---> URL : 127.0.0.1:8000/posts/{ ID}/edit  (method: GET)

    Route::put('/{id}', [PostController::class, 'update'])->name('update');
    // ---> URL : 127.0.0.1:8000/posts/{ ID}  (method: PUT)


    Route::delete('/{id}', [PostController::class, 'destroy'])->name('destroy');
    // ---> URL : 127.0.0.1:8000/posts/{ ID}  (method : DELETE)
});

Route::get('/category/{id}/post', [CategoryController::class, 'index'])->name('category-list-post');


Route::get('/category', [CategoryController::class, 'index'])->name('category-list');


Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'handleLoginForm'])->name('login.handle');
Route::post('logout', [LoginController::class, 'logout'])->name('logout');

Route::get('profile', [ProfileController::class, 'showProfile'])->name('profile')->middleware('check_login_user');

Route::post('subscribe_post', [SubscribePostController::class, 'store'])->name('subscribe_post');

Route::get('test-send-mail', [TestSendMailController::class, 'send'])->name('test-send-mail');

Route::get('/ajax', [AjaxApiController::class, 'index'])->name('api.index');


Route::get('/test-email', [JobController::class, 'index'])->name('test-email');

// Route::get('test-email', 'JobController@processQueue');

Route::get('/file-import', [UserController::class, 'importView'])->name('import-view');
Route::post('/import', [UserController::class, 'import'])->name('import');
Route::get('/export-users', [UserController::class, 'exportUsers'])->name('export-users');

// Route::post('/import', UserController::class, 'importView')->name('import');


Route::get('/import-with-queue',[UserQueueController::class, 'import_with_queue'])->name('import-with-queue');
Route::post('/import-queue', [UserQueueController::class, 'import-queue'])->name('import-queue');

app/Models/Comment.php
<?php

namespace App\Models;

use Carbon\Factory;
use Database\Factories\CommentFactory;
use Faker\Factory as FakerFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    use HasFactory;


    protected $fillable = [
        'post_id',
        'user_id',
        'content',
        
    ];
 
       /**
    * Get the category that owns the post.
    */
   public function comment()
   {
       // case 1: viết ngắn gọn
       return $this->belongsTo(Comment::class);


       // case 2: viết đầy đủ 
       // return $this->belongsTo(Category::class, 'category_id', 'id');
   }

       /**
     * Create a new factory instance for the model.
     */

}

app/Http/Controllers/Admin/CommentController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Comment;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $data = [];
        

        $comments=Comment::with('category')->paginate(11);
        $data['comments']= $comments;
        return view('backend.comments.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/backend/comments/_search.blade.php
<div class="d-flex justify-content-between mb-3">
    <div>
        {{-- create category link --}}
        <a href="{{ route('admin.posts.create') }}" class="btn btn-primary"><i class="fas fa-plus"></i> {{ __('Tạo') }}</a>

        @if(!$posts->isEmpty())
            {{ __('Tổng số bản ghi', ['total' => $posts->count()]) }}
        @endif
    </div>
    <div>
        <form action="{{ route('admin.posts.index') }}" method="get">
            <input type="text" placeholder="" name="name" value="{{ request()->name }}" class="form-control-custom d-inline-block">
            <button type="submit" class="btn btn-primary d-inline-block"><i class="fas fa-search"></i> {{ __('Tìm kiếm') }}</button>
        </form>
    </div>
</div>

resources/views/backend/comments/index.blade.php
@extends('backend.layouts.master')

{{-- set page title --}}
@section('title', __('message.category_list'))

{{-- set breadcrumbName --}}
@section('breadcrumbName', __('Danh sách bài viết'))

{{-- set breadcrumbMenu --}}
@section('breadcrumbMenu', __('message.category_list'))

{{-- import file css (private) --}}
@push('css')
    <link rel="stylesheet" href="/backend/css/categories/category-list.css">
@endpush

@section('content')
    {{-- form search --}}
    @include('backend.comments._search')

    {{-- show message --}}
    @if(Session::has('success'))
        <p class="text-success">{{ Session::get('success') }}</p>
    @endif

    {{-- show error message --}}
    @if(Session::has('error'))
        <p class="text-danger">{{ Session::get('error') }}</p>
    @endif

    {{-- display list category table --}}
    @if($comments->isEmpty())
        <p class="red">{{ __('Không tìm thấy dữ liệu') }}</p>
    @else
        <table id="category-list" class="table table-bordered table-hover table-striped">
            <thead class="bg-info">
                <tr>
                    <th class="text-center">#</th>
                    <th>ID bài viết</th>
                    <th>ID người dùng</th>
                    <th> Nội dung</th>
                    <th colspan="2">Thao tác</th>
                </tr>
            </thead>
            <tbody>
                @if(!empty($comments))
                    @foreach ($comments as $key => $comment)
                        <tr>
                            <td class="text-center">{{ $key+1 }}</td>
                            <td>{{ $comment->name }}</td>
                            <td> {{ $comment->category->name}} </td>
                            <td>{{ $comment->content }}</td>
                            <td><a href="{{ route('admin.comments.edit', $comment->id) }}" class="btn btn-info btn-common" title="{{ __('message.edit_comment') }}"><i class="fas fa-edit"></i> {{ __('Chỉnh sửa') }}</a></td>
                            <td>
                                    <form action="{{ route('admin.comments.destroy', $post->id) }}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger btn-common" onclick="return confirm('bạn có muốn xóa không ?')"><i class="fas fa-trash-alt"></i> {{ __('Xóa') }}</button>
                                    </form>
                            </td>
                        </tr>
                    @endforeach
                @endif
            </tbody>
        </table>
    @endif
@endsection