routes/admin.php
<?php

use App\Http\Controllers\Admin\AuthController;
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\PostController;
use App\Models\Comment;
use Encore\Admin\Grid\Displayers\Prefix;
use Illuminate\Support\Facades\Route;

use PhpParser\Node\Name;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/



Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'check_login_admin'], function () {

// Route::group(['middleware' => ['check_login_admin'], 'as' => 'admin.'], function () {

    // Route::group(['prefix' => 'admin.',  'middleware' => 'CheckAdminLogin'], function(){


    Route::get('login', [AuthController::class, 'getLogin'])->name('login');
    Route::post('login', [AuthController::class, 'postLogin'])->name('login.handle');
    Route::post('logout', [AuthController::class, 'logout'])->name('logout');

    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');


    Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
        Route::get('/', [CategoryController::class, 'index'])->name('index');
        Route::get('/create', [CategoryController::class, 'create'])->name('create');
        Route::post('/store', [CategoryController::class, 'store'])->name('store');
        Route::get('/{id}/show', [CategoryController::class, 'show'])->name('show');
        Route::get('/{id}/edit', [CategoryController::class, 'edit'])->name('edit');
        Route::put('/{id}/update', [CategoryController::class, 'update'])->name('update');
        Route::delete('/{id}/delete', [CategoryController::class, 'destroy'])->name('destroy');
    });

    Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {
        Route::get('/', [PostController::class, 'index'])->name('index');
        Route::get('/create', [PostController::class, 'create'])->name('create');
        Route::post('/store', [PostController::class, 'store'])->name('store');
        Route::get('/{id}/show', [PostController::class, 'show'])->name('show');
        Route::get('/{id}/edit', [PostController::class, 'edit'])->name('edit');
        Route::put('/{id}/update', [PostController::class, 'update'])->name('update');
        Route::delete('/{id}/delete', [PostController::class, 'destroy'])->name('destroy');
        Route::post('/{id}/save-feature', [PostController::class, 'saveFeature'])->name('save-feature');
    });

    Route::group(['prefix' => 'comments', 'as' => 'comments.'], function () {
        Route::get('/', [Comment::class, 'index'])->name('index');
    });
});








// Route::group(['middleware' => ['check_login_admin'] , 'as' => 'admin.'], function () {

//     Route::resource('category','CategoryController');

// 	// Admin Dashboard
// 	Route::get('/', [DashboardController::class, 'index'])->name('dashboard');	

//     // route for module Category
// 	Route::group(['prefix' => 'category', 'as' => 'category.'], function () {
//         Route::get('/', [CategoryController::class, 'index'])->name('index');
//         Route::get('/create', [CategoryController::class, 'create'])->name('create');
//         Route::post('/store', [CategoryController::class, 'store'])->name('store');
//         Route::get('/{id}/show', [CategoryController::class, 'show'])->name('show');
//         Route::get('/{id}/edit', [CategoryController::class, 'edit'])->name('edit');
//         Route::put('/{id}/update', [CategoryController::class, 'update'])->name('update');
//         Route::delete('/{id}/delete', [CategoryController::class, 'destroy'])->name('destroy');
//     });

//     Route::group(['prefix' => 'posts', 'as' => 'posts.'], function() {
//         Route::get('/', [PostController::class, 'index'])->name('index');
//         Route::get('/create', [PostController::class, 'create'])->name('create');
//         Route::post('/store', [PostController::class, 'store'])->name('store');
//         Route::get('/{id}/show', [PostController::class, 'show'])->name('show');
//         Route::get('/{id}/edit', [PostController::class, 'edit'])->name('edit');
//         Route::put('/{id}/update', [PostController::class, 'update'])->name('update');
//     });

// });

routes/web.php
<?php

use App\Http\Controllers\AjaxApiController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\ProfileController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\SubscribePostController;
use App\Http\Controllers\UserQueueController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\TestSendMailController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/




require __DIR__ . '/admin.php';

require __DIR__ . '/auth.php';


Route::get('/', [HomeController::class, 'index'])->name('home');

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');

Route::get('/posts', [PostController::class, 'index'])->name('posts.index');

// Route::PostController::class->group(function () {
//     Route::get('/posts', 'show');
//     Route::post('/post', 'store');
// });

// Route::prefix('/posts')-> group(function() {
//     Route::get('/', [PostController::class, 'index'])->name('index');

// })-> name('posts.');


Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {
    Route::get('/', [PostController::class, 'index'])->name('index');
    // ---> URL : 127.0.0.1:8000/posts (method : GET)

    Route::get('/create', [PostController::class, 'create'])->name('create');
    // ---> URL : 127.0.0.1:8000/posts/create (method : GET)


    Route::post('/', [PostController::class, 'store'])->name('store');
    // ---> URL : 127.0.0.1:8000/posts (method: POST)


    Route::get('/{id}', [PostController::class, 'show'])->name('show');
    // ---> URL : 127.0.0.1:8000/posts/{post ID}   (method : GET)


    Route::get('/{id}/edit', [PostController::class, 'edit'])->name('edit');
    // ---> URL : 127.0.0.1:8000/posts/{ ID}/edit  (method: GET)

    Route::put('/{id}', [PostController::class, 'update'])->name('update');
    // ---> URL : 127.0.0.1:8000/posts/{ ID}  (method: PUT)


    Route::delete('/{id}', [PostController::class, 'destroy'])->name('destroy');
    // ---> URL : 127.0.0.1:8000/posts/{ ID}  (method : DELETE)
});

Route::get('/category/{id}/post', [CategoryController::class, 'index'])->name('category-list-post');


Route::get('/category', [CategoryController::class, 'index'])->name('category-list');


Route::get('login', [LoginController::class, 'showLoginForm'])->name('login');
Route::post('login', [LoginController::class, 'handleLoginForm'])->name('login.handle');
Route::post('logout', [LoginController::class, 'logout'])->name('logout');

Route::get('profile', [ProfileController::class, 'showProfile'])->name('profile')->middleware('check_login_user');

Route::post('subscribe_post', [SubscribePostController::class, 'store'])->name('subscribe_post');

Route::get('test-send-mail', [TestSendMailController::class, 'send'])->name('test-send-mail');

Route::get('/ajax', [AjaxApiController::class, 'index'])->name('api.index');


Route::get('/test-email', [JobController::class, 'index'])->name('test-email');

// Route::get('test-email', 'JobController@processQueue');

Route::get('/file-import', [UserController::class, 'importView'])->name('import-view');
Route::post('/import', [UserController::class, 'import'])->name('import');
Route::get('/export-users', [UserController::class, 'exportUsers'])->name('export-users');

// Route::post('/import', UserController::class, 'importView')->name('import');


Route::get('/import-with-queue',[UserQueueController::class, 'import_with_queue'])->name('import-with-queue');
Route::post('/import-queue', [UserQueueController::class, 'import-queue'])->name('import-queue');

app/Models/Category.php
<?php

namespace App\Models;

use Database\Factories\CategoryFactory;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
    ];

    /**
     * Get the posts for the category.
     */
    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    /**
     * Create a new factory instance for the model.
     */
    protected static function newFactory(): Factory
    {
        return CategoryFactory::new();
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\Category\StoreCategoryRequest;
use App\Models\Category;
use Encore\Admin\Form\Builder;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class CategoryController extends Controller
{
    private $category;
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $data = [];
        $categories = Category::withCount('posts')->get();
        $data['categories'] = $categories;

        return view('backend.categories.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $data = [];


        return view('backend.categories.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreCategoryRequest $request)
    {
        // insert to DB
        $categoryInsert = [
            'name' => $request->category_name
        ];

        try {
            // Insert into data to table category (successful)
            Category::create($categoryInsert);

            return redirect()->route('admin.category.index')
                ->with('sucess', trans('message.store_category_success'));
        } catch (\Exception $ex) {
            // Insert into data to table category (fail)
            Log::error($ex->getMessage());
            return redirect()->back()->with('error', $ex->getMessage());
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $data = [];
        $category = Category::findOrFail($id);
        $data['category'] = $category;

        return view('backend.categories.edit', $data);  
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        try {
            // Create $category
            $category = Category::findOrFail($id);

            // Set value for field name
            $category->name = $request->category_name;

            $category->save();

            return redirect()->route('admin.category.index')
                ->with('success', trans('Thành Công'));
        } catch (\Exception $ex) {
            // Have error so will show error message
            return redirect()->back()->with('error', $ex->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $category = Category::findOrFail($id);

        /**
         * Check Login Before Delete Category ID
         *
         * @check          CategoryID have exist into table products
         * @@relation_key: products.category_id = categories.id
         *
         * @if   ($count > 0) then show error message (because Category ID have exist into table products)
         * @else then can delete this category (because Category ID dont exist into table products)
         */
        $count = Category::whereDoesntHave('posts')
            ->exists();

        try {
            if ($count) {
                /**
                 * @step1 FindOrFail to check Category ID have exist into Database
                 * @step2 Delete Record
                 */
                $category->delete();

                return redirect()->route('admin.category.index')
                    ->with('success', trans('message.delete_category_success'));
            }

            // if: true then show error message
            return redirect()->route('admin.category.index')
                ->with('error', trans('message.delete_category_fail'));
            

        } catch (\Exception $ex) {
            // Have error so will show error message
            return redirect()->back()->with('error', $ex->getMessage());
        }
    }
}

app/Http/Controllers/Api/CategoryController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Resources\CategoryResource;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        
        $categories= Category::all();
        return CategoryResource::collection($categories);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $data = [
            'name'=> $request->name, 
        
        ];
        $category = Category::create($data);
        return new CategoryResource($category);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $category = Category::findOrFail($id);
        return new CategoryResource($category);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $category = Category::findOrFail($id);

        $dataUpdate = [
            'name'=>$request->name,
        ];
        $category->update($dataUpdate);
        return new CategoryResource($category);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $category = Category::findOrFail($id);
        $category->delete();
        return response()->json(['message'=>'xoa thanh cong']);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function index(Request $request, $id)
    {
        $data = [];
        $keyword = $request->keyword;
        if (!empty($keyword)) {
            $posts = Post::with('category')
                ->where('category_id', $id)
                ->where('name', 'like', '%' . $keyword . '%')
                ->paginate(12);
        } else {
            $posts = Post::with('category')
                ->where('category_id', $id)
                ->paginate(12);
        }

        $data['posts'] = $posts;
        return view('categories.index', $data);
    }
}

resources/views/backend/categories/_search.blade.php
<div class="d-flex justify-content-between mb-3">
    <div>
        {{-- create category link --}}
        <a href="{{ route('admin.category.create') }}" class="btn btn-primary"><i class="fas fa-plus"></i> {{ __('Tạo') }}</a>

        @if(!$categories->isEmpty())
            {{ __('Tổng số bản ghi', ['total' => $categories->count()]) }}
        @endif
    </div>
    <div>
        <form action="{{ route('admin.category.index') }}" method="get">
            <input type="text" placeholder="" name="name" value="{{ request()->name }}" class="form-control-custom d-inline-block">
            <button type="submit" class="btn btn-primary d-inline-block"><i class="fas fa-search"></i> {{ __('Tìm kiếm') }}</button>
        </form>
    </div>
</div>

resources/views/backend/categories/create.blade.php
@extends('backend.layouts.master')

{{-- set page title --}}
@section('title', __('message.create_category'))

{{-- set breadcrumbName --}}
@section('breadcrumbName', __('Danh sách category'))

{{-- set breadcrumbMenu --}}
@section('breadcrumbMenu', __('message.create_category'))

{{-- import file css (private) --}}
@push('css')
    <link rel="stylesheet" href="/backend/css/categories/category-create.css">
@endpush

@section('content')
    {{-- error message --}}
    @include('errors.error_message')

    <form action="{{ route('admin.category.store') }}" method="post">
        @csrf
        <div class="row">
            <div class="col-md-4">
                <div class="form-group">
                    <label for="" class="required">{{ __('Tên category') }}</label>
                    <input type="text" name="category_name" class="form-control">
                    @error('category_name')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
        </div>

        <p><span class="red">(*)</span> {{ __('Bắt buộc') }}</p>

        <div class="form-group">
            <a href="{{ route('admin.category.index') }}" class="btn btn-secondary"><i class="fas fa-long-arrow-alt-left"></i> <span class="ml-2">{{ __('Trở về') }}</span></a>
            <button type="submit" class="btn btn-primary"><i class="fas fa-save"></i> <span class="ml-2">{{ __('Cập nhật') }}</span></button>
        </div>
    </form>
@endsection

resources/views/backend/categories/detail.blade.php
@extends('backend.layouts.master')

{{-- set page title --}}
@section('title', 'Detail Category')

{{-- set breadcrumbName --}}
@section('breadcrumbName', 'Category Management')

{{-- set breadcrumbMenu --}}
@section('breadcrumbMenu', 'Detail Category')

{{-- import file css (private) --}}
@push('css')

@endpush

@section('content')
    
@endsection

resources/views/backend/categories/edit.blade.php
@extends('backend.layouts.master')

{{-- set page title --}}
@section('title', __('message.edit_category'))

{{-- set breadcrumbName --}}
@section('breadcrumbName', __('Danh sách category'))

{{-- set breadcrumbMenu --}}
@section('breadcrumbMenu', __('message.edit_category'))

{{-- import file css (private) --}}
@push('css')
    <link rel="stylesheet" href="/backend/css/categories/category-edit.css">
@endpush

@section('content')
    {{-- error message --}}
    @include('errors.error_message')

    <form action="{{ route('admin.category.update', $category->id) }}" method="post">
        @csrf
        @method('PUT')

        <div class="form-group mb-3">
            <div class="row">
                <div class="col-md-4">
                    <label for="" class="required">{{ __('Tên category') }}</label>
                    <input type="text" name="category_name" value="{{ old('category_name', $category->name) }}" class="form-control">
                    @error('category_name')
                        <div class="text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
        </div>
        
        <p><span class="red">(*)</span> {{ __('Bắt buộc') }}</p>

        <div class="form-group">
            <a href="{{ route('admin.category.index') }}" class="btn btn-secondary"><i class="fas fa-long-arrow-alt-left"></i> <span class="ml-2">{{ __('Trở về') }}</span></a>
            <button type="submit" class="btn btn-primary"><i class="far fa-edit"></i> <span class="ml-2">{{ __('Cập nhật') }}</span></button>
        </div>
    </form>
@endsection

resources/views/backend/categories/index.blade.php
@extends('backend.layouts.master')

{{-- set page title --}}
@section('title', __('message.category_list'))

{{-- set breadcrumbName --}}
@section('breadcrumbName', __('Danh sách category'))

{{-- set breadcrumbMenu --}}
@section('breadcrumbMenu', __('message.category_list'))

{{-- import file css (private) --}}
@push('css')
    <link rel="stylesheet" href="/backend/css/categories/category-list.css">
@endpush

@section('content')
    {{-- form search --}}
    @include('backend.categories._search')

    {{-- show message --}}
    @if(Session::has('success'))
        <p class="text-success">{{ Session::get('success') }}</p>
    @endif

    {{-- show error message --}}
    @if(Session::has('error'))
        <p class="text-danger">{{ Session::get('error') }}</p>
    @endif

    {{-- display list category table --}}
    @if($categories->isEmpty())
        <p class="red">{{ __('message.not_found_data') }}</p>
    @else
        <table id="category-list" class="table table-bordered table-hover table-striped">
            <thead class="bg-info">
                <tr>
                    <th class="text-center">#</th>
                    <th> Tên category</th>
                    <th>Số lượng bài viết</th>
                    <th colspan="2">Thao tác</th>
                </tr>
            </thead>
            <tbody>
                @if(!empty($categories))
                    @foreach ($categories as $key => $category)
                        <tr>
                            <td class="text-center">{{ $key+1 }}</td>
                            <td>{{ $category->name }}</td>
                            <td><a href="{{ route('admin.posts.index', ['category_id[]' => $category->id]) }}" class="btn btn-link btn-common"><i class="fas fa-search-plus"></i><span class="ml-2">Số lượng bài viết(<span class="font-weight-bold">{{ $category->posts_count }}</span>)</span></a></td>
                            <td><a href="{{ route('admin.category.edit', $category->id) }}" class="btn btn-info btn-common" title="{{ __('message.edit_product') }}"><i class="fas fa-edit"></i> {{ __('Chỉnh sửa') }}</a></td>
                            <td>
                                @if($category->posts_count  == 0)
                                    <form action="{{ route('admin.category.destroy', $category->id) }}" method="post">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger btn-common" onclick="return confirm('bạn có muốn xóa không ?')"><i class="fas fa-trash-alt"></i> {{ __('Xóa') }}</button>
                                    </form>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                @endif
            </tbody>
        </table>
    @endif
@endsection